const BASE_INVENTORY = [
  {
    title: '2021 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2021,
    price: 29500,
    mileage: 729771,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1FUJHHDR1LLKS7083',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2016 Kenworth T880',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T880',
    year: 2016,
    price: 78700,
    mileage: 77836,
    state: 'GA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKDDP9X5GJ463782',
    rep: 'CTTS',
    location: 'GA'
  },
  {
    title: '2011 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2011,
    price: 29500,
    mileage: 728375,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJSJNXBN421820',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2016 Kenworth T880',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T880',
    year: 2016,
    price: 67200,
    mileage: 447797,
    state: 'FL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1NKDXPBX8GJ443755',
    rep: 'CTTS',
    location: 'FL'
  },
  {
    title: '2016 Kenworth T680 Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 708090,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYDP9X5GJ463964',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2016,
    price: 29500,
    mileage: 669947,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD57GSHZ3174',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2018 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2018,
    price: 44800,
    mileage: 646281,
    state: 'AR',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDRXJSJV6552',
    rep: 'CTTS',
    location: 'AR'
  },
  {
    title: '2016 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2016,
    price: 29500,
    mileage: 618999,
    state: 'AL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR1GN106358',
    rep: 'CTTS',
    location: 'AL'
  },
  {
    title: '2013 Kenworth T680 Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Sleeper Truck',
    year: 2013,
    price: 32800,
    mileage: 615039,
    state: 'OH',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKAD29X2DJ364792',
    rep: 'IAA',
    location: 'OH'
  },
  {
    title: '2001 Mack CH613',
    type: 'Truck',
    brand: 'Mack',
    model: 'CH613',
    year: 2001,
    price: 15560,
    mileage: 560000,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1M2P267C51M047405',
    rep: 'IAA',
    location: 'TX'
  },
  {
    title: '2017 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2017,
    price: 37200,
    mileage: 534234,
    state: 'VA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR3HN510187',
    rep: 'CTTS',
    location: 'VA'
  },
  {
    title: '2019 International LT625',
    type: 'Truck',
    brand: 'International',
    model: 'LT625',
    year: 2019,
    price: 37200,
    mileage: 486459,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDZAPR9KN921980',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 28250,
    mileage: 480622,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD59ESFS9745',
    rep: 'Copart',
    location: 'TN'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 29500,
    mileage: 469777,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1FUJGLDV0ELFD1390',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2014 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2014,
    price: 28250,
    mileage: 458183,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD55ESFU9482',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2015 International ProStar',
    type: 'Truck',
    brand: 'International',
    model: 'ProStar',
    year: 2015,
    price: 29500,
    mileage: 441488,
    state: 'CO',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR5FN607571',
    rep: 'CTTS',
    location: 'CO'
  },
  {
    title: '2013 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2013,
    price: 26000,
    mileage: 611872,
    state: 'NJ',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EH4DN135570',
    rep: 'IAA',
    location: 'NJ'
  },
  {
    title: '2016 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2016,
    price: 31000,
    mileage: 399999,
    state: 'IL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EH7GN968675',
    rep: 'CTTS',
    location: 'IL'
  },
  {
    title: '2016 International Prostar',
    type: 'Truck',
    brand: 'International',
    model: 'Prostar',
    year: 2016,
    price: 29500,
    mileage: 394014,
    state: 'MA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HSDJAPR5GN106294',
    rep: 'CTTS',
    location: 'MA'
  },
  {
    title: '2016 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 336751,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X0GJ474120',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2016 Volvo VNL64T',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL64T',
    year: 2016,
    price: 34100,
    mileage: 319612,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EJ3GN949920',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2013 Freightliner Cascadia',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia',
    year: 2013,
    price: 0,
    mileage: 336225,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLBG0DSFU9299',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2013 Freightliner Cascadia',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia',
    year: 2013,
    price: 0,
    mileage: 146705,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDV9DSBJ3753',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2014 International TerraStar',
    type: 'Truck',
    brand: 'International',
    model: 'TerraStar',
    year: 2014,
    price: 0,
    mileage: 0,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3HAMMMMM1EL770410',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2019 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2019,
    price: 39400,
    mileage: 664545,
    state: 'FL',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1NPBD49X7KD232764',
    rep: 'Remarkete place',
    location: 'FL'
  },
  {
    title: '2016 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 644737,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X9GJ494772',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2014 Freightliner Sleeper Truck',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Sleeper Truck',
    year: 2014,
    price: 28250,
    mileage: 458183,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLD5XESFS9307',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2015 Peterbilt 389',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389',
    year: 2015,
    price: 36480,
    mileage: 529920,
    state: 'GA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDB9X7FD287357',
    rep: 'Remarkete place',
    location: 'GA'
  },
  {
    title: '2016 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 658966,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49X7GD356631',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2017 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2017,
    price: 39400,
    mileage: 561936,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49XXHD401380',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2013 Freightliner Cascadia FT125SLP',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia FT125SLP',
    year: 2013,
    price: 0,
    mileage: 132344,
    state: 'CA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '3AKJGLDR3DSBS2767',
    rep: 'CTTS',
    location: 'CA'
  },
  {
    title: '2017 Kenworth Sleeper Truck',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'Sleeper Truck',
    year: 2017,
    price: 39400,
    mileage: 381800,
    state: 'NJ',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XKYD49X9HJ117680',
    rep: 'Remarkete place',
    location: 'NJ'
  },
  {
    title: '2016 Peterbilt Sleeper Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: 'Sleeper Truck',
    year: 2016,
    price: 39400,
    mileage: 633806,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBD49X0GD336287',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Peterbilt 579',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579',
    year: 2016,
    price: 39400,
    mileage: 761233,
    state: 'TN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDP9X8GD330978',
    rep: 'CTTS',
    location: 'TN'
  },
  {
    title: '2016 Peterbilt 389',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389',
    year: 2016,
    price: 39400,
    mileage: 577492,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '1XPBDB9X7GD297979',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2020 Volvo VNL760',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL760',
    year: 2020,
    price: 84500,
    mileage: 412880,
    state: 'WA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '4V4NC9EH0LN876543',
    rep: 'MT',
    location: 'WA'
  },
  {
    title: '2022 Peterbilt 579 Ultraloft',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579 Ultraloft',
    year: 2022,
    price: 118900,
    mileage: 186200,
    state: 'NJ',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1XPBDP9X2ND785410',
    rep: 'MT',
    location: 'NJ'
  },
  {
    title: '2019 Freightliner M2 106 Box Truck',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'M2 106 Box',
    year: 2019,
    price: 65900,
    mileage: 298440,
    state: 'IL',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1FVACWFC1KHLP3321',
    rep: 'MT',
    location: 'IL'
  },
  {
    title: '2021 Kenworth T680 Next Gen',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Next Gen',
    year: 2021,
    price: 109500,
    mileage: 265900,
    state: 'MO',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1XKYD49X0MJ423876',
    rep: 'MT',
    location: 'MO'
  },
  {
    title: '2018 International LT625 Sleeper',
    type: 'Truck',
    brand: 'International',
    model: 'LT625 Sleeper',
    year: 2018,
    price: 52400,
    mileage: 502000,
    state: 'IN',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3HSDZAPR8JN234987',
    rep: 'MT',
    location: 'IN'
  },
  {
    title: '2023 Utility 3000R Reefer Trailer',
    type: 'Trailer',
    brand: 'Utility',
    model: '3000R Reefer',
    year: 2023,
    price: 78900,
    mileage: 12000,
    state: 'FL',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1UYVS2535P3004590',
    rep: 'CTTS',
    location: 'FL'
  },
  {
    title: '2020 Vanguard Dry Van Trailer',
    type: 'Trailer',
    brand: 'Vanguard',
    model: 'Dry Van',
    year: 2020,
    price: 34950,
    mileage: 15500,
    state: 'OH',
    status: 'Available',
    dealStatus: 'Open',
    vin: '5V8VC5325LT209876',
    rep: 'IAA',
    location: 'OH'
  },
  {
    title: '2019 Delucio Flatbed Trailer',
    type: 'Trailer',
    brand: 'Delucio',
    model: 'Flatbed',
    year: 2019,
    price: 28900,
    mileage: 22400,
    state: 'MS',
    status: 'Available',
    dealStatus: 'Open',
    vin: '7D2BE4025KM123450',
    rep: 'MT',
    location: 'MS'
  },
  {
    title: '2022 Freightliner Cascadia 126',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia 126',
    year: 2022,
    price: 102500,
    mileage: 198345,
    state: 'PA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3AKJHHDR5NSME2450',
    rep: 'CTTS',
    location: 'PA'
  },
  {
    title: '2018 Peterbilt 389 Long Hood',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389 Long Hood',
    year: 2018,
    price: 97400,
    mileage: 432100,
    state: 'OK',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1NPXLP9X0JD485012',
    rep: 'MT',
    location: 'OK'
  },
  {
    title: '2015 Volvo VNL670',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL670',
    year: 2015,
    price: 41900,
    mileage: 643220,
    state: 'NC',
    status: 'Available',
    dealStatus: 'Open',
    vin: '4V4NC9EH2FN912340',
    rep: 'CTTS',
    location: 'NC'
  },
  {
    title: '2021 Kenworth W990',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'W990',
    year: 2021,
    price: 128400,
    mileage: 174500,
    state: 'UT',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1NKZL49X0MJ205678',
    rep: 'CTTS',
    location: 'UT'
  },
  {
    title: '2019 International MV607 Box Truck',
    type: 'Truck',
    brand: 'International',
    model: 'MV607 Box Truck',
    year: 2019,
    price: 58900,
    mileage: 256880,
    state: 'CO',
    status: 'Available',
    dealStatus: 'Open',
    vin: '3HAEUMML9KL248901',
    rep: 'IAA',
    location: 'CO'
  },
  {
    title: '2020 Utility Curtain Side Trailer',
    type: 'Trailer',
    brand: 'Utility',
    model: 'Curtain Side',
    year: 2020,
    price: 45500,
    mileage: 18000,
    state: 'GA',
    status: 'Available',
    dealStatus: 'Open',
    vin: '1UYCS2530L1009876',
    rep: 'MT',
    location: 'GA'
  },
  {
    title: '2018 Vanguard Reefer Trailer',
    type: 'Trailer',
    brand: 'Vanguard',
    model: 'Reefer',
    year: 2018,
    price: 36500,
    mileage: 40200,
    state: 'SC',
    status: 'Available',
    dealStatus: 'Open',
    vin: '5V8VC5323JT204578',
    rep: 'CTTS',
    location: 'SC'
  },
  {
    title: '2022 Peterbilt 579 UltraLoft',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579 UltraLoft',
    year: 2022,
    price: 128500,
    mileage: 184200,
    state: 'TX',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1XPBDP9X0ND789123',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2021 Volvo VNL760 Sleeper',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL760 Sleeper',
    year: 2021,
    price: 114900,
    mileage: 201400,
    state: 'GA',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '4V4NC9EJ9MN123654',
    rep: 'IAA',
    location: 'GA'
  },
  {
    title: '2019 Freightliner Cascadia Day Cab',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia Day Cab',
    year: 2019,
    price: 76500,
    mileage: 342110,
    state: 'IL',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '3AKJGLD59KSKL8821',
    rep: 'MT',
    location: 'IL'
  },
  {
    title: '2018 Kenworth T680 Day Cab',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Day Cab',
    year: 2018,
    price: 68900,
    mileage: 415778,
    state: 'OK',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1XKYD49X7JJ234567',
    rep: 'CTTS',
    location: 'OK'
  },
  {
    title: '2020 International HX620 Dump Truck',
    type: 'Truck',
    brand: 'International',
    model: 'HX620 Dump Truck',
    year: 2020,
    price: 134500,
    mileage: 158990,
    state: 'PA',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1HTXHAPT0LH764321',
    rep: 'CTTS',
    location: 'PA'
  },
  {
    title: '2021 Mack Anthem 64T',
    type: 'Truck',
    brand: 'Mack',
    model: 'Anthem 64T',
    year: 2021,
    price: 99950,
    mileage: 276540,
    state: 'NC',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1M1AN4GY8MM025789',
    rep: 'IAA',
    location: 'NC'
  },
  {
    title: '2017 Great Dane Champion Dry Van',
    type: 'Trailer',
    brand: 'Great Dane',
    model: 'Champion Dry Van',
    year: 2017,
    price: 24500,
    mileage: 11200,
    state: 'IN',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1GR1A0624HJ304560',
    rep: 'Copart',
    location: 'IN'
  },
  {
    title: '2020 Wabash ArcticLite Reefer',
    type: 'Trailer',
    brand: 'Wabash',
    model: 'ArcticLite Reefer',
    year: 2020,
    price: 53800,
    mileage: 8900,
    state: 'WI',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1JJV532D5LL279845',
    rep: 'CTTS',
    location: 'WI'
  },
  {
    title: '2022 Fontaine Infinity Flatbed',
    type: 'Trailer',
    brand: 'Fontaine',
    model: 'Infinity Flatbed',
    year: 2022,
    price: 46800,
    mileage: 7200,
    state: 'AL',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '13N2482C2N1532098',
    rep: 'MT',
    location: 'AL'
  },
  {
    title: '2023 Utility 4000DX Dry Van',
    type: 'Trailer',
    brand: 'Utility',
    model: '4000DX Dry Van',
    year: 2023,
    price: 52900,
    mileage: 3500,
    state: 'NJ',
    status: 'Sold',
    dealStatus: 'Closed',
    vin: '1UYVS2535P3901245',
    rep: 'CTTS',
    location: 'NJ'
  },
  {
    title: '2018 Volvo VNL760',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL760',
    year: 2018,
    price: 61200,
    mileage: 521400,
    state: 'WA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4V4NC9EH6JN895001',
    rep: 'CTTS',
    location: 'WA'
  },
  {
    title: '2019 Volvo VNL860',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL860',
    year: 2019,
    price: 68950,
    mileage: 434880,
    state: 'OR',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4V4NC9EH7KN224578',
    rep: 'IAA',
    location: 'OR'
  },
  {
    title: '2020 Peterbilt 579',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579',
    year: 2020,
    price: 74200,
    mileage: 389200,
    state: 'UT',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XPBDP9X4LD715432',
    rep: 'MT',
    location: 'UT'
  },
  {
    title: '2021 Peterbilt 567 Day Cab',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '567 Day Cab',
    year: 2021,
    price: 88600,
    mileage: 254100,
    state: 'CO',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XPCDP9X2MD743219',
    rep: 'CTTS',
    location: 'CO'
  },
  {
    title: '2017 Peterbilt 389',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '389',
    year: 2017,
    price: 92500,
    mileage: 498220,
    state: 'ND',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XPXD49X8HD738210',
    rep: 'IAA',
    location: 'ND'
  },
  {
    title: '2016 Volvo VNL670',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL670',
    year: 2016,
    price: 45200,
    mileage: 612440,
    state: 'MN',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EH3GN951347',
    rep: 'Copart',
    location: 'MN'
  },
  {
    title: '2015 Volvo VNM 200 Day Cab',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNM 200',
    year: 2015,
    price: 31800,
    mileage: 554900,
    state: 'KY',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4V4M19GH3FN921045',
    rep: 'CTTS',
    location: 'KY'
  },
  {
    title: '2022 Peterbilt 579 Ultraloft',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '579 Ultraloft',
    year: 2022,
    price: 105400,
    mileage: 175600,
    state: 'ID',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XPBDP9X2ND802145',
    rep: 'CTTS',
    location: 'ID'
  },
  {
    title: '2018 Mack Pinnacle CXU613',
    type: 'Truck',
    brand: 'Mack',
    model: 'Pinnacle CXU613',
    year: 2018,
    price: 52800,
    mileage: 511300,
    state: 'SC',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1M1AW07Y2JM085421',
    rep: 'IAA',
    location: 'SC'
  },
  {
    title: '2020 Mack Anthem 64T',
    type: 'Truck',
    brand: 'Mack',
    model: 'Anthem 64T',
    year: 2020,
    price: 87800,
    mileage: 301200,
    state: 'NV',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1M1AN4GY7LM026781',
    rep: 'CTTS',
    location: 'NV'
  },
  {
    title: '2019 Mack Granite GU713 Dump',
    type: 'Truck',
    brand: 'Mack',
    model: 'Granite GU713',
    year: 2019,
    price: 118500,
    mileage: 162300,
    state: 'ME',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1M2AX09C2KM031245',
    rep: 'CTTS',
    location: 'ME'
  },
  {
    title: '2021 Mack LR64 Garbage Truck',
    type: 'Truck',
    brand: 'Mack',
    model: 'LR64',
    year: 2021,
    price: 226500,
    mileage: 85600,
    state: 'MA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1M2LR3GC1MM026934',
    rep: 'IAA',
    location: 'MA'
  },
  {
    title: '2017 Peterbilt 337 Box Truck',
    type: 'Truck',
    brand: 'Peterbilt',
    model: '337 Box Truck',
    year: 2017,
    price: 59800,
    mileage: 241500,
    state: 'OK',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '2NP2HM6X2HM472380',
    rep: 'Copart',
    location: 'OK'
  },
  {
    title: '2016 International DuraStar 4300',
    type: 'Truck',
    brand: 'International',
    model: 'DuraStar 4300',
    year: 2016,
    price: 42800,
    mileage: 215400,
    state: 'MO',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1HTMMMML9GH206789',
    rep: 'CTTS',
    location: 'MO'
  },
  {
    title: '2018 Freightliner M2 106 Box Truck',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'M2 106',
    year: 2018,
    price: 49500,
    mileage: 198700,
    state: 'LA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1FVACXFD3JHJS8432',
    rep: 'IAA',
    location: 'LA'
  },
  {
    title: '2020 Hino 268A Dry Van',
    type: 'Truck',
    brand: 'Hino',
    model: '268A',
    year: 2020,
    price: 52900,
    mileage: 152300,
    state: 'MS',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '5PVNE8JV0L4S54001',
    rep: 'CTTS',
    location: 'MS'
  },
  {
    title: '2021 Isuzu NPR-HD Reefer',
    type: 'Truck',
    brand: 'Isuzu',
    model: 'NPR-HD Reefer',
    year: 2021,
    price: 49800,
    mileage: 88200,
    state: 'NM',
    status: 'Stock',
    dealStatus: 'Open',
    vin: 'JALC4W168M7K03521',
    rep: 'CTTS',
    location: 'NM'
  },
  {
    title: '2019 Ford F-750 Dump',
    type: 'Truck',
    brand: 'Ford',
    model: 'F-750 Dump',
    year: 2019,
    price: 78800,
    mileage: 91300,
    state: 'WV',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1FDNF7DC6KDF04213',
    rep: 'MT',
    location: 'WV'
  },
  {
    title: '2018 Freightliner Cascadia CNG',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia CNG',
    year: 2018,
    price: 52500,
    mileage: 402800,
    state: 'OH',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '3AKJHHDR5JDJM3942',
    rep: 'CTTS',
    location: 'OH'
  },
  {
    title: '2022 Volvo VNR300 Day Cab',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNR300',
    year: 2022,
    price: 91500,
    mileage: 121400,
    state: 'IL',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4V4WC9EG1NN256302',
    rep: 'IAA',
    location: 'IL'
  },
  {
    title: '2023 Volvo VNR640',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNR640',
    year: 2023,
    price: 122900,
    mileage: 48200,
    state: 'MI',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4V4WC9EG2PN721540',
    rep: 'CTTS',
    location: 'MI'
  },
  {
    title: '2022 Freightliner Cascadia 116',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia 116',
    year: 2022,
    price: 112700,
    mileage: 98800,
    state: 'AZ',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '3AKJHHDR0NSNR1456',
    rep: 'CTTS',
    location: 'AZ'
  },
  {
    title: '2021 Freightliner Cascadia 126',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'Cascadia 126',
    year: 2021,
    price: 101300,
    mileage: 141600,
    state: 'AR',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '3AKJHHDR2MSMA6520',
    rep: 'IAA',
    location: 'AR'
  },
  {
    title: '2019 Freightliner M2 112 Tandem',
    type: 'Truck',
    brand: 'Freightliner',
    model: 'M2 112',
    year: 2019,
    price: 88500,
    mileage: 182200,
    state: 'DE',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1FVAG3CV2KHKL9345',
    rep: 'CTTS',
    location: 'DE'
  },
  {
    title: '2017 Volvo VNL430 Midroof',
    type: 'Truck',
    brand: 'Volvo',
    model: 'VNL430',
    year: 2017,
    price: 39800,
    mileage: 598200,
    state: 'IA',
    status: 'Stock',
    dealStatus: 'Closed',
    vin: '4V4NC9EG7HN964210',
    rep: 'Copart',
    location: 'IA'
  },
  {
    title: '2018 Kenworth T680 Day Cab',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Day Cab',
    year: 2018,
    price: 52400,
    mileage: 432900,
    state: 'KS',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XKYD49X0JJ216540',
    rep: 'CTTS',
    location: 'KS'
  },
  {
    title: '2020 Kenworth T880 Dump',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T880 Dump',
    year: 2020,
    price: 142600,
    mileage: 156300,
    state: 'NE',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1NKZLP0X7LJ387214',
    rep: 'MT',
    location: 'NE'
  },
  {
    title: '2021 Kenworth W990',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'W990',
    year: 2021,
    price: 138900,
    mileage: 188500,
    state: 'SD',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XKWD49X0MJ390164',
    rep: 'CTTS',
    location: 'SD'
  },
  {
    title: '2022 Kenworth T680 Next Gen',
    type: 'Truck',
    brand: 'Kenworth',
    model: 'T680 Next Gen',
    year: 2022,
    price: 126500,
    mileage: 104300,
    state: 'MT',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1XKYD49X3NJ456201',
    rep: 'CTTS',
    location: 'MT'
  },
  {
    title: '2019 Utility 3000R Reefer',
    type: 'Trailer',
    brand: 'Utility',
    model: '3000R Reefer',
    year: 2019,
    price: 49800,
    mileage: 9800,
    state: 'FL',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1UYVS2530K7701245',
    rep: 'IAA',
    location: 'FL'
  },
  {
    title: '2018 Great Dane Everest TL',
    type: 'Trailer',
    brand: 'Great Dane',
    model: 'Everest TL',
    year: 2018,
    price: 45900,
    mileage: 12500,
    state: 'GA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1GRAP0628JJ209854',
    rep: 'Copart',
    location: 'GA'
  },
  {
    title: '2020 Hyundai Translead Dry Van',
    type: 'Trailer',
    brand: 'Hyundai',
    model: 'Translead Dry Van',
    year: 2020,
    price: 38200,
    mileage: 8800,
    state: 'TX',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '3H3V532C3LT255401',
    rep: 'CTTS',
    location: 'TX'
  },
  {
    title: '2021 Stoughton Z-Plate Dry Van',
    type: 'Trailer',
    brand: 'Stoughton',
    model: 'Z-Plate Dry Van',
    year: 2021,
    price: 41800,
    mileage: 5400,
    state: 'NC',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1DW1A5326MS619845',
    rep: 'CTTS',
    location: 'NC'
  },
  {
    title: '2022 Reitnouer Big Bubba Flatbed',
    type: 'Trailer',
    brand: 'Reitnouer',
    model: 'Big Bubba Flatbed',
    year: 2022,
    price: 54800,
    mileage: 6100,
    state: 'PA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1RNF53A29NR048521',
    rep: 'IAA',
    location: 'PA'
  },
  {
    title: '2023 MAC Aluminum Flatbed',
    type: 'Trailer',
    brand: 'MAC',
    model: 'Aluminum Flatbed',
    year: 2023,
    price: 62800,
    mileage: 3100,
    state: 'OH',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '5MADA4823PR065412',
    rep: 'CTTS',
    location: 'OH'
  },
  {
    title: '2019 Benson All Aluminum Flatbed',
    type: 'Trailer',
    brand: 'Benson',
    model: 'All Aluminum Flatbed',
    year: 2019,
    price: 47800,
    mileage: 9900,
    state: 'VA',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '5DMJF5325KP002874',
    rep: 'CTTS',
    location: 'VA'
  },
  {
    title: '2020 Manac Combo Drop Deck',
    type: 'Trailer',
    brand: 'Manac',
    model: 'Combo Drop Deck',
    year: 2020,
    price: 51900,
    mileage: 7200,
    state: 'NJ',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '2M5131610L1138945',
    rep: 'CTTS',
    location: 'NJ'
  },
  {
    title: '2021 Pitts LT40 Log Trailer',
    type: 'Trailer',
    brand: 'Pitts',
    model: 'LT40 Log Trailer',
    year: 2021,
    price: 33800,
    mileage: 4500,
    state: 'AL',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1P9LT4022MA083214',
    rep: 'IAA',
    location: 'AL'
  },
  {
    title: '2022 Trail King TK80HDG Lowboy',
    type: 'Trailer',
    brand: 'Trail King',
    model: 'TK80HDG',
    year: 2022,
    price: 134800,
    mileage: 2500,
    state: 'MT',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1TKJ05333NM092451',
    rep: 'CTTS',
    location: 'MT'
  },
  {
    title: '2023 XL Specialized RGN Lowboy',
    type: 'Trailer',
    brand: 'XL Specialized',
    model: 'RGN Lowboy',
    year: 2023,
    price: 148900,
    mileage: 1800,
    state: 'WY',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4U3J04837PR062480',
    rep: 'CTTS',
    location: 'WY'
  },
  {
    title: '2021 East Genesis Frameless Dump',
    type: 'Trailer',
    brand: 'East',
    model: 'Genesis Frameless Dump',
    year: 2021,
    price: 72800,
    mileage: 3900,
    state: 'IN',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1E1D2H287MR077542',
    rep: 'IAA',
    location: 'IN'
  },
  {
    title: '2019 Timpte Super Hopper Grain',
    type: 'Trailer',
    brand: 'Timpte',
    model: 'Super Hopper',
    year: 2019,
    price: 49800,
    mileage: 7100,
    state: 'KS',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1TDH42226KB159340',
    rep: 'CTTS',
    location: 'KS'
  },
  {
    title: '2020 Wilson Pacesetter Grain',
    type: 'Trailer',
    brand: 'Wilson',
    model: 'Pacesetter Grain',
    year: 2020,
    price: 51200,
    mileage: 6800,
    state: 'NE',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1W16532A6L6612840',
    rep: 'CTTS',
    location: 'NE'
  },
  {
    title: '2021 Doonan Chaparral Steel Flat',
    type: 'Trailer',
    brand: 'Doonan',
    model: 'Chaparral Steel Flat',
    year: 2021,
    price: 47800,
    mileage: 5200,
    state: 'OK',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1D9F53238MA634025',
    rep: 'MT',
    location: 'OK'
  },
  {
    title: '2022 Featherlite 53ft Drop Deck',
    type: 'Trailer',
    brand: 'Featherlite',
    model: '53ft Drop Deck',
    year: 2022,
    price: 68800,
    mileage: 3600,
    state: 'CO',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '4FGA53239NC155480',
    rep: 'CTTS',
    location: 'CO'
  },
  {
    title: '2018 Fontaine Revolution 52',
    type: 'Trailer',
    brand: 'Fontaine',
    model: 'Revolution 52',
    year: 2018,
    price: 43800,
    mileage: 10400,
    state: 'WI',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '13N2532C7J1579345',
    rep: 'IAA',
    location: 'WI'
  },
  {
    title: '2020 Vanguard VXP Dry Van',
    type: 'Trailer',
    brand: 'Vanguard',
    model: 'VXP Dry Van',
    year: 2020,
    price: 39800,
    mileage: 9300,
    state: 'IL',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '5V8VC5325LT305942',
    rep: 'CTTS',
    location: 'IL'
  },
  {
    title: '2021 Strick Dry Van',
    type: 'Trailer',
    brand: 'Strick',
    model: 'Dry Van',
    year: 2021,
    price: 40500,
    mileage: 7200,
    state: 'NY',
    status: 'Stock',
    dealStatus: 'Open',
    vin: '1S12E9538MD517842',
    rep: 'CTTS',
    location: 'NY'
  }
];

const ENGINE_OPTIONS = [
  'Detroit DD15 / 505 HP',
  'Cummins X15 / 500 HP',
  'Volvo D13 / 455 HP',
  'PACCAR MX-13 / 455 HP',
  'Cummins ISX15 / 450 HP',
  'Detroit DD13 / 470 HP',
  'Volvo D11 / 405 HP',
  'PACCAR MX-11 / 430 HP',
  'Cummins X12 / 455 HP',
  'International A26 / 475 HP'
];

const TRANSMISSION_OPTIONS = [
  '12-speed automatic',
  '10-speed manual',
  '13-speed manual',
  '18-speed manual',
  'Endurant 12-speed auto',
  'Allison 6-speed automatic'
];

const LOCATION_BANK = [
  { city: 'Los Angeles', state: 'CA' },
  { city: 'Dallas', state: 'TX' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'Orlando', state: 'FL' },
  { city: 'Salt Lake City', state: 'UT' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Kansas City', state: 'MO' }
];

const PHONE_BANK = [
  '+1 (310) 555-0147',
  '+1 (972) 555-0188',
  '+1 (470) 555-0114',
  '+1 (773) 555-0106',
  '+1 (602) 555-0199',
  '+1 (215) 555-0132',
  '+1 (407) 555-0121',
  '+1 (385) 555-0155',
  '+1 (629) 555-0178',
  '+1 (816) 555-0166'
];

const FEATURE_LIBRARY = [
  ['Sleeper cab', 'APU', 'Aluminum wheels', 'Full aero kit'],
  ['Collision mitigation', 'Lane assist', 'Disc brakes all around'],
  ['Fresh PM service', 'Clean title', 'No active faults'],
  ['New drive tires', 'DOT ready', 'Maintenance records'],
  ['Thermo King APU', 'Bunk heater', 'Fridge & inverter'],
  ['Alloy wheels', 'Air ride suspension', 'Fresh detail'],
  ['Sliding tandems', 'Air ride', 'Steel frame'],
  ['Logistics posts', 'Aluminum roof', 'Translucent roof'],
  ['Scale certified', 'E-logs ready', 'Bluetooth audio'],
  ['Fresh brakes', 'LED lighting', 'Recent alignment']
];

const FALLBACK_IMAGES = [
  'https://imagescdn.dealercarsearch.com/Media/22484/23001914/638930206131273528.jpg',
  'https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg',
  'https://images.pexels.com/photos/2199294/pexels-photo-2199294.jpeg',
  'https://images.pexels.com/photos/2199295/pexels-photo-2199295.jpeg',
  'https://images.pexels.com/photos/2199296/pexels-photo-2199296.jpeg',
  'https://images.pexels.com/photos/2199297/pexels-photo-2199297.jpeg',
  'https://images.pexels.com/photos/21694/pexels-photo.jpg'
];

const COLOR_PALETTE = ['White','Red','Blue','Black','Silver','Gray','Green','Maroon','Navy','Charcoal'];
const MAX_GALLERY_IMAGES = 10;

function deriveModel(title = '', brand = '') {
  const cleaned = title.replace(/\b(19|20)\d{2}\b/, '').replace(new RegExp(brand, 'i'), '').replace(/\s+/g, ' ').trim();
  return cleaned || 'Model';
}

function gallerySeed(unit = {}) {
  const key = (unit.vin || unit.title || 'unit').toString();
  const cleaned = key.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
  return cleaned || 'unit';
}

function buildGallery(unit, idx) {
  const seed = gallerySeed(unit);
  const primaryImage = unit.image || FALLBACK_IMAGES[idx % FALLBACK_IMAGES.length];
  const baseGallery = Array.isArray(unit.images) ? unit.images.filter(Boolean) : [];
  const placeholders = Array.from({ length: MAX_GALLERY_IMAGES }, (_, i) => `https://picsum.photos/seed/${seed}-${i}/900/600`);
  const gallery = [primaryImage, ...baseGallery, ...placeholders, FALLBACK_IMAGES[(idx + 3) % FALLBACK_IMAGES.length]]
    .filter(Boolean);
  return [...new Set(gallery)].slice(0, MAX_GALLERY_IMAGES);
}

const INVENTORY_SEED = BASE_INVENTORY.map((unit, idx) => {
  const location = LOCATION_BANK[idx % LOCATION_BANK.length];
  const state = unit.state && unit.state !== 'Unknown' && unit.state !== 'Other' ? unit.state : location.state;
  const color = unit.color && unit.color !== 'Unknown' && unit.color !== 'Other' ? unit.color : COLOR_PALETTE[idx % COLOR_PALETTE.length];
  const gallery = buildGallery(unit, idx);
  const description = unit.description || `${unit.year || 'Late-model'} ${unit.brand || ''} ${deriveModel(unit.title, unit.brand)} ready for work with clean title and recent service.`.trim();
  const features = Array.isArray(unit.features) && unit.features.length ? unit.features : FEATURE_LIBRARY[idx % FEATURE_LIBRARY.length];

  return {
    ...unit,
    state,
    color,
    model: unit.model || deriveModel(unit.title, unit.brand),
    engine: unit.engine || ENGINE_OPTIONS[idx % ENGINE_OPTIONS.length],
    transmission: unit.transmission || TRANSMISSION_OPTIONS[idx % TRANSMISSION_OPTIONS.length],
    condition: unit.condition || (idx % 6 === 0 ? 'New' : 'Used'),
    location: unit.location || `${location.city}, ${location.state}`,
    phone: unit.phone || PHONE_BANK[idx % PHONE_BANK.length],
    description,
    features,
    images: [...new Set(gallery)],
    image: gallery[0],
    price: unit.price ?? 0,
    mileage: unit.mileage ?? 0,
    status: unit.status || 'Available'
  };
}).slice(0, 100);

// Expose the seed globally so inline scripts on static pages can access it.
if (typeof globalThis !== 'undefined') {
  globalThis.BASE_INVENTORY = BASE_INVENTORY;
  globalThis.INVENTORY_SEED = INVENTORY_SEED;
}
